# fly.toml file generated for discord-reacji-channeler on 2023-03-21T23:17:31+09:00

app = "discord-reacji-channeler"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "nrt"
processes = []

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = false

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"
